version: '2'
services:
  master:
    build: .
    environment:
      - WALE_S3_PREFIX=s3://
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=ap-northeast-1
      - POSTGRES_PASSWORD=
    volumes:
      - ./data/master:/var/lib/postgresql/data
    ports:
      - 5432:5432
