version: '2'
services:
  master:
    build: .
    environment:
      - WALE_AWS_ACCESS_KEY_ID=
      - WALE_AWS_SECRET_ACCESS_KEY=
      - WALE_S3_ENDPOINT=https+path://
    volumes:
      - ./data/master:/var/lib/postgresql/data
